import { ThemeDefinition, ThemeId, ThemeTypography } from './types';

/** System-only stacks (offline-safe in Tauri, zero licensing risk). */
export const STACK_SERIF_WARM = '"Charter", Georgia, "Times New Roman", serif';
export const STACK_SERIF_BOOK = 'Georgia, "Times New Roman", "Nimbus Roman", serif';
export const STACK_SANS_CLEAN = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
export const STACK_SANS_HUMAN = '"Avenir Next", "Segoe UI", system-ui, sans-serif';
export const STACK_MONO = 'ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace';

/** Mirror of editor/canvas getPresetStyleVariables for a bundled theme block. */
export function themeTypographyToVars(t: ThemeTypography): Record<string, string> {
  return {
    '--editor-font-family': t.bodyStack,
    '--editor-heading-family': t.headingStack,
    '--editor-font-size': `${t.baseSizePx}px`,
    '--editor-line-height': `${t.lineHeight}`,
    '--editor-max-width': `${t.maxWidthPx}px`,
    '--manuscript-page-width': `${t.maxWidthPx}px`,
    '--editor-paragraph-margin':
      t.paragraph === 'spacious' ? '1.5em' : t.paragraph === 'compact' ? '0.85em' : '0.4em',
    '--editor-text-indent': t.indent ? '1.5em' : '0',
  };
}

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  studio: {
    id: 'studio',
    name: 'Studio',
    description: 'Clean, neutral desk with balanced slate accents',
    mode: 'light',
    moodGroup: 'Studio Essentials',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 18, lineHeight: 1.85, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#f9f8f6', '#ffffff', '#4a5568'],
    tokens: {
      appBg: '#f9f8f6',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#2b2b2b',
      textSecondary: '#5a5855',
      textMuted: '#8c8983',
      accent: '#4a5568',
      accentFg: '#ffffff',
      borderQuiet: '#eae7e1',
      divider: '#f0ede6',
      selectionBg: '#dbeafe',
      selectionFg: '#1e3a8a',
      cursorColor: '#2b2b2b',
      sidebarBg: '#ffffff',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#2b2b2b',
      linkColor: '#2563eb',
      codeBg: '#f3f0e8',
      blockquoteBorder: '#cbd5e1',
      colorSuccess: '#10b981',
      colorWarning: '#f59e0b',
      colorError: '#ef4444',
      focusRing: 'rgba(74, 85, 104, 0.4)',
      modalOverlay: 'rgba(0, 0, 0, 0.45)',
      statusBarBg: '#ffffff',
      scrollbarThumb: '#d1cdc4',
    },
  },

  oled: {
    id: 'oled',
    name: 'OLED Black',
    description: 'Pure pitch black for minimum eye fatigue and true OLED screens',
    mode: 'dark',
    moodGroup: 'Night Writing',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 16, lineHeight: 1.7, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#000000', '#0a0a0a', '#60a5fa'],
    tokens: {
      appBg: '#000000',
      appSurface: '#080808',
      appSurfaceElevated: '#121212',
      textPrimary: '#f3f4f6',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
      accent: '#60a5fa',
      accentFg: '#000000',
      borderQuiet: '#1f2937',
      divider: '#111827',
      selectionBg: '#1e3a8a',
      selectionFg: '#ffffff',
      cursorColor: '#60a5fa',
      sidebarBg: '#000000',
      editorCanvasBg: '#080808',
      editorTextColor: '#f3f4f6',
      linkColor: '#93c5fd',
      codeBg: '#111827',
      blockquoteBorder: '#374151',
      colorSuccess: '#34d399',
      colorWarning: '#fbbf24',
      colorError: '#f87171',
      focusRing: 'rgba(96, 165, 250, 0.5)',
      modalOverlay: 'rgba(0, 0, 0, 0.85)',
      statusBarBg: '#000000',
      scrollbarThumb: '#374151',
    },
  },

  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Electric neon cyan & magenta across dark obsidian night',
    mode: 'dark',
    moodGroup: 'Vivid & Playful',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 16, lineHeight: 1.7, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#0d0e15', '#161826', '#00f0ff'],
    tokens: {
      appBg: '#0d0e15',
      appSurface: '#161826',
      appSurfaceElevated: '#1f2338',
      textPrimary: '#f0f6fc',
      textSecondary: '#a5b4fc',
      textMuted: '#6366f1',
      accent: '#00f0ff',
      accentFg: '#050811',
      borderQuiet: '#2a2f4c',
      divider: '#1e2238',
      selectionBg: '#ff007f',
      selectionFg: '#ffffff',
      cursorColor: '#00f0ff',
      sidebarBg: '#12141f',
      editorCanvasBg: '#161826',
      editorTextColor: '#f0f6fc',
      linkColor: '#00f0ff',
      codeBg: '#1e2238',
      blockquoteBorder: '#ff007f',
      colorSuccess: '#00ff66',
      colorWarning: '#ffb700',
      colorError: '#ff0055',
      focusRing: 'rgba(0, 240, 255, 0.5)',
      modalOverlay: 'rgba(5, 8, 17, 0.8)',
      statusBarBg: '#12141f',
      scrollbarThumb: '#3b426b',
    },
  },

  nord: {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic blue-grey tones inspired by Scandinavian landscapes',
    mode: 'dark',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 16, lineHeight: 1.7, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#2e3440', '#3b4252', '#88c0d0'],
    tokens: {
      appBg: '#2e3440',
      appSurface: '#3b4252',
      appSurfaceElevated: '#434c5e',
      textPrimary: '#eceff4',
      textSecondary: '#d8dee9',
      textMuted: '#e5e9f0',
      accent: '#88c0d0',
      accentFg: '#2e3440',
      borderQuiet: '#4c566a',
      divider: '#3b4252',
      selectionBg: '#434c5e',
      selectionFg: '#88c0d0',
      cursorColor: '#88c0d0',
      sidebarBg: '#2e3440',
      editorCanvasBg: '#3b4252',
      editorTextColor: '#eceff4',
      linkColor: '#81a1c1',
      codeBg: '#2e3440',
      blockquoteBorder: '#81a1c1',
      colorSuccess: '#a3be8c',
      colorWarning: '#ebcb8b',
      colorError: '#bf616a',
      focusRing: 'rgba(136, 192, 208, 0.4)',
      modalOverlay: 'rgba(46, 52, 64, 0.75)',
      statusBarBg: '#2e3440',
      scrollbarThumb: '#4c566a',
    },
  },

  solarized: {
    id: 'solarized',
    name: 'Solarized Dark',
    description: 'Precision-calculated warm dark palette with amber and cyan highlights',
    mode: 'dark',
    moodGroup: 'Night Writing',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SERIF_BOOK,
      baseSizePx: 17, lineHeight: 1.75, maxWidthPx: 800,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#002b36', '#073642', '#b58900'],
    tokens: {
      appBg: '#002b36',
      appSurface: '#073642',
      appSurfaceElevated: '#0a4250',
      textPrimary: '#93a1a1',
      textSecondary: '#8fa3a3',
      textMuted: '#7ba3a3',
      accent: '#b58900',
      accentFg: '#002b36',
      borderQuiet: '#0e5264',
      divider: '#073642',
      selectionBg: '#073642',
      selectionFg: '#eee8d5',
      cursorColor: '#268bd2',
      sidebarBg: '#002b36',
      editorCanvasBg: '#073642',
      editorTextColor: '#93a1a1',
      linkColor: '#268bd2',
      codeBg: '#002b36',
      blockquoteBorder: '#2aa198',
      colorSuccess: '#859900',
      colorWarning: '#cb4b16',
      colorError: '#dc322f',
      focusRing: 'rgba(181, 137, 0, 0.4)',
      modalOverlay: 'rgba(0, 43, 54, 0.8)',
      statusBarBg: '#002b36',
      scrollbarThumb: '#0e5264',
    },
  },

  nordic_day: {
    id: 'nordic_day',
    name: 'Nordic Day',
    description: 'Crisp, bright snow aesthetic with glacial blue accents',
    mode: 'light',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 16, lineHeight: 1.7, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#eceff4', '#ffffff', '#5e81ac'],
    tokens: {
      appBg: '#eceff4',
      appSurface: '#ffffff',
      appSurfaceElevated: '#f8fafc',
      textPrimary: '#2e3440',
      textSecondary: '#4c566a',
      textMuted: '#7c8b9e',
      accent: '#5e81ac',
      accentFg: '#ffffff',
      borderQuiet: '#d8dee9',
      divider: '#e5e9f0',
      selectionBg: '#d8dee9',
      selectionFg: '#2e3440',
      cursorColor: '#5e81ac',
      sidebarBg: '#ffffff',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#2e3440',
      linkColor: '#5e81ac',
      codeBg: '#e5e9f0',
      blockquoteBorder: '#88c0d0',
      colorSuccess: '#a3be8c',
      colorWarning: '#ebcb8b',
      colorError: '#bf616a',
      focusRing: 'rgba(94, 129, 172, 0.4)',
      modalOverlay: 'rgba(46, 52, 64, 0.4)',
      statusBarBg: '#ffffff',
      scrollbarThumb: '#c2cad6',
    },
  },

  literary: {
    id: 'literary',
    name: 'Literary',
    description: 'Warm cream, soft amber, and deep bookish ink',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 18, lineHeight: 1.85, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#fbf0d9', '#fff9ed', '#8c5e3c'],
    tokens: {
      appBg: '#fbf0d9',
      appSurface: '#fff9ed',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#3d2b1f',
      textSecondary: '#6e5442',
      textMuted: '#9e8470',
      accent: '#8c5e3c',
      accentFg: '#ffffff',
      borderQuiet: '#eddcc2',
      divider: '#f5e9d3',
      selectionBg: '#edd9b9',
      selectionFg: '#3d2b1f',
      cursorColor: '#8c5e3c',
      sidebarBg: '#fdf6e7',
      editorCanvasBg: '#fff9ed',
      editorTextColor: '#3d2b1f',
      linkColor: '#9c411d',
      codeBg: '#f3e4cb',
      blockquoteBorder: '#bfa07d',
      colorSuccess: '#4d8055',
      colorWarning: '#c77826',
      colorError: '#ad372b',
      focusRing: 'rgba(140, 94, 60, 0.4)',
      modalOverlay: 'rgba(61, 43, 31, 0.45)',
      statusBarBg: '#fdf6e7',
      scrollbarThumb: '#dbc7aa',
    },
  },

  typewriter: {
    id: 'typewriter',
    name: 'Typewriter Desk',
    description: 'Classic vintage newsroom paper and ribbon monochrome',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_MONO,
      headingStack: STACK_MONO,
      baseSizePx: 16, lineHeight: 2.0, maxWidthPx: 800,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#eae6df', '#f4f1ea', '#333333'],
    tokens: {
      appBg: '#eae6df',
      appSurface: '#f4f1ea',
      appSurfaceElevated: '#faf8f4',
      textPrimary: '#1a1a1a',
      textSecondary: '#4d4d4d',
      textMuted: '#808080',
      accent: '#333333',
      accentFg: '#ffffff',
      borderQuiet: '#d5cfc4',
      divider: '#dfdacd',
      selectionBg: '#d0c9bb',
      selectionFg: '#1a1a1a',
      cursorColor: '#000000',
      sidebarBg: '#eeeae2',
      editorCanvasBg: '#f4f1ea',
      editorTextColor: '#1a1a1a',
      linkColor: '#1a1a1a',
      codeBg: '#ded8cc',
      blockquoteBorder: '#736e65',
      colorSuccess: '#3e6b48',
      colorWarning: '#9e6d22',
      colorError: '#9e2d24',
      focusRing: 'rgba(51, 51, 51, 0.4)',
      modalOverlay: 'rgba(26, 26, 26, 0.5)',
      statusBarBg: '#eeeae2',
      scrollbarThumb: '#bfb8a8',
    },
  },

  ink_and_paper: {
    id: 'ink_and_paper',
    name: 'Ink & Paper',
    description: 'High-contrast stark print layout with editorial precision',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SERIF_BOOK,
      baseSizePx: 17, lineHeight: 1.75, maxWidthPx: 800,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#f5f5f5', '#ffffff', '#000000'],
    tokens: {
      appBg: '#f5f5f5',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#000000',
      textSecondary: '#404040',
      textMuted: '#737373',
      accent: '#000000',
      accentFg: '#ffffff',
      borderQuiet: '#e0e0e0',
      divider: '#ebebeb',
      selectionBg: '#000000',
      selectionFg: '#ffffff',
      cursorColor: '#000000',
      sidebarBg: '#ffffff',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#000000',
      linkColor: '#000000',
      codeBg: '#ebebeb',
      blockquoteBorder: '#000000',
      colorSuccess: '#16a34a',
      colorWarning: '#ca8a04',
      colorError: '#dc2626',
      focusRing: 'rgba(0, 0, 0, 0.6)',
      modalOverlay: 'rgba(0, 0, 0, 0.6)',
      statusBarBg: '#ffffff',
      scrollbarThumb: '#b3b3b3',
    },
  },

  midnight_blue: {
    id: 'midnight_blue',
    name: 'Midnight Blue',
    description: 'Deep oceanic indigo night with crisp starlight accents',
    mode: 'dark',
    moodGroup: 'Night Writing',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 16, lineHeight: 1.7, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#0b132b', '#1c2541', '#48cae4'],
    tokens: {
      appBg: '#0b132b',
      appSurface: '#1c2541',
      appSurfaceElevated: '#243054',
      textPrimary: '#e0f2fe',
      textSecondary: '#93c5fd',
      textMuted: '#60a5fa',
      accent: '#48cae4',
      accentFg: '#0b132b',
      borderQuiet: '#2c3a66',
      divider: '#1f2b4e',
      selectionBg: '#3a506b',
      selectionFg: '#ffffff',
      cursorColor: '#48cae4',
      sidebarBg: '#111a36',
      editorCanvasBg: '#1c2541',
      editorTextColor: '#e0f2fe',
      linkColor: '#38bdf8',
      codeBg: '#111a36',
      blockquoteBorder: '#48cae4',
      colorSuccess: '#2dd4bf',
      colorWarning: '#f59e0b',
      colorError: '#fb7185',
      focusRing: 'rgba(72, 202, 228, 0.45)',
      modalOverlay: 'rgba(11, 19, 43, 0.8)',
      statusBarBg: '#111a36',
      scrollbarThumb: '#3a506b',
    },
  },

  forest_night: {
    id: 'forest_night',
    name: 'Forest Night',
    description: 'Evergreen pine, moss shadow, and gentle golden firefly glow',
    mode: 'dark',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 18, lineHeight: 1.85, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#131c15', '#1e2d22', '#a3cfbb'],
    tokens: {
      appBg: '#131c15',
      appSurface: '#1e2d22',
      appSurfaceElevated: '#283c2e',
      textPrimary: '#e8f5e9',
      textSecondary: '#a5d6a7',
      textMuted: '#66bb6a',
      accent: '#a3cfbb',
      accentFg: '#131c15',
      borderQuiet: '#2f4736',
      divider: '#203225',
      selectionBg: '#2f4736',
      selectionFg: '#ffffff',
      cursorColor: '#a3cfbb',
      sidebarBg: '#162219',
      editorCanvasBg: '#1e2d22',
      editorTextColor: '#e8f5e9',
      linkColor: '#81c784',
      codeBg: '#162219',
      blockquoteBorder: '#81c784',
      colorSuccess: '#4caf50',
      colorWarning: '#ffca28',
      colorError: '#e57373',
      focusRing: 'rgba(163, 207, 187, 0.45)',
      modalOverlay: 'rgba(19, 28, 21, 0.8)',
      statusBarBg: '#162219',
      scrollbarThumb: '#3e5c46',
    },
  },

  sepia_desk: {
    id: 'sepia_desk',
    name: 'Sepia Desk',
    description: 'Rich vintage leather, warm antique paper, and bronze trims',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SERIF_BOOK,
      baseSizePx: 17, lineHeight: 1.75, maxWidthPx: 800,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#ede0d4', '#f7ede2', '#7f5539'],
    tokens: {
      appBg: '#ede0d4',
      appSurface: '#f7ede2',
      appSurfaceElevated: '#fff6ec',
      textPrimary: '#43281c',
      textSecondary: '#6b442a',
      textMuted: '#9c6644',
      accent: '#7f5539',
      accentFg: '#ffffff',
      borderQuiet: '#ddb892',
      divider: '#e6ccb2',
      selectionBg: '#ddb892',
      selectionFg: '#43281c',
      cursorColor: '#7f5539',
      sidebarBg: '#f0e3d7',
      editorCanvasBg: '#f7ede2',
      editorTextColor: '#43281c',
      linkColor: '#9c6644',
      codeBg: '#e6ccb2',
      blockquoteBorder: '#7f5539',
      colorSuccess: '#588157',
      colorWarning: '#d48b38',
      colorError: '#bc4749',
      focusRing: 'rgba(127, 85, 57, 0.4)',
      modalOverlay: 'rgba(67, 40, 28, 0.5)',
      statusBarBg: '#f0e3d7',
      scrollbarThumb: '#cca378',
    },
  },

  crimson_gothic: {
    id: 'crimson_gothic',
    name: 'Crimson Gothic',
    description: 'Velvet burgundy, obsidian stone, and deep ruby luminescence',
    mode: 'dark',
    moodGroup: 'Gothic & Moody',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 18, lineHeight: 1.85, maxWidthPx: 820,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#161114', '#241a20', '#e63946'],
    tokens: {
      appBg: '#161114',
      appSurface: '#241a20',
      appSurfaceElevated: '#33232d',
      textPrimary: '#fae8eb',
      textSecondary: '#d8b4bc',
      textMuted: '#9e7580',
      accent: '#e63946',
      accentFg: '#ffffff',
      borderQuiet: '#422c39',
      divider: '#2a1e26',
      selectionBg: '#592938',
      selectionFg: '#ffffff',
      cursorColor: '#e63946',
      sidebarBg: '#1c151a',
      editorCanvasBg: '#241a20',
      editorTextColor: '#fae8eb',
      linkColor: '#ff4d6d',
      codeBg: '#1c151a',
      blockquoteBorder: '#e63946',
      colorSuccess: '#52b788',
      colorWarning: '#ee9b00',
      colorError: '#e63946',
      focusRing: 'rgba(230, 57, 70, 0.45)',
      modalOverlay: 'rgba(22, 17, 20, 0.85)',
      statusBarBg: '#1c151a',
      scrollbarThumb: '#4e3343',
    },
  },

  arctic_light: {
    id: 'arctic_light',
    name: 'Arctic Light',
    description: 'Ultra-crisp frost daylight with crystalline blue contrasts',
    mode: 'light',
    moodGroup: 'Studio Essentials',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 15, lineHeight: 1.55, maxWidthPx: 840,
      paragraph: 'compact', indent: false,
    },
    swatchColors: ['#f0f4f8', '#ffffff', '#0284c7'],
    tokens: {
      appBg: '#f0f4f8',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#0f172a',
      textSecondary: '#334155',
      textMuted: '#64748b',
      accent: '#0284c7',
      accentFg: '#ffffff',
      borderQuiet: '#cbd5e1',
      divider: '#e2e8f0',
      selectionBg: '#bae6fd',
      selectionFg: '#0369a1',
      cursorColor: '#0284c7',
      sidebarBg: '#f8fafc',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#0f172a',
      linkColor: '#0284c7',
      codeBg: '#e2e8f0',
      blockquoteBorder: '#38bdf8',
      colorSuccess: '#059669',
      colorWarning: '#d97706',
      colorError: '#e11d48',
      focusRing: 'rgba(2, 132, 199, 0.4)',
      modalOverlay: 'rgba(15, 23, 42, 0.45)',
      statusBarBg: '#f8fafc',
      scrollbarThumb: '#94a3b8',
    },
  },

  monochrome: {
    id: 'monochrome',
    name: 'Monochrome Slate',
    description: 'Minimalist pure grayscale with zero chromatic distraction',
    mode: 'dark',
    moodGroup: 'Studio Essentials',
    typography: {
      bodyStack: STACK_SANS_CLEAN,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 15, lineHeight: 1.55, maxWidthPx: 840,
      paragraph: 'compact', indent: false,
    },
    swatchColors: ['#18181b', '#27272a', '#a1a1aa'],
    tokens: {
      appBg: '#18181b',
      appSurface: '#27272a',
      appSurfaceElevated: '#3f3f46',
      textPrimary: '#fafafa',
      textSecondary: '#d4d4d8',
      textMuted: '#a1a1aa',
      accent: '#e4e4e7',
      accentFg: '#18181b',
      borderQuiet: '#3f3f46',
      divider: '#27272a',
      selectionBg: '#52525b',
      selectionFg: '#ffffff',
      cursorColor: '#ffffff',
      sidebarBg: '#1f1f23',
      editorCanvasBg: '#27272a',
      editorTextColor: '#fafafa',
      linkColor: '#e4e4e7',
      codeBg: '#18181b',
      blockquoteBorder: '#71717a',
      colorSuccess: '#4ade80',
      colorWarning: '#facc15',
      colorError: '#f87171',
      focusRing: 'rgba(228, 228, 231, 0.4)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#1f1f23',
      scrollbarThumb: '#52525b',
    },
  },

  newsprint: {
    id: 'newsprint',
    name: 'Newsprint',
    description: 'Morning broadsheet greys with a restrained umber accent',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SANS_HUMAN,
      baseSizePx: 17, lineHeight: 1.8, maxWidthPx: 780,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#f2efe9', '#fbfaf7', '#7c5a2d'],
    tokens: {
      appBg: '#f2efe9',
      appSurface: '#fbfaf7',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#23211c',
      textSecondary: '#4c463a',
      textMuted: '#6e6656',
      accent: '#7c5a2d',
      accentFg: '#ffffff',
      borderQuiet: '#ddd5c6',
      divider: '#e7e0d2',
      selectionBg: '#e3d3ae',
      selectionFg: '#23211c',
      cursorColor: '#7c5a2d',
      sidebarBg: '#f6f3ec',
      editorCanvasBg: '#fbfaf7',
      editorTextColor: '#23211c',
      linkColor: '#5b4a1f',
      codeBg: '#e9e2d3',
      blockquoteBorder: '#a8977a',
      colorSuccess: '#3e6b48',
      colorWarning: '#9e6d22',
      colorError: '#9e2d24',
      focusRing: 'rgba(124, 90, 45, 0.4)',
      modalOverlay: 'rgba(35, 33, 28, 0.45)',
      statusBarBg: '#f6f3ec',
      scrollbarThumb: '#c2b8a3',
    },
  },

  lavender_morning: {
    id: 'lavender_morning',
    name: 'Lavender Morning',
    description: 'Soft violet dawn haze with plum ink for gentle starts',
    mode: 'light',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_HUMAN,
      baseSizePx: 18, lineHeight: 1.9, maxWidthPx: 800,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#f1edf9', '#faf8fe', '#6d4fc2'],
    tokens: {
      appBg: '#f1edf9',
      appSurface: '#faf8fe',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#2b2340',
      textSecondary: '#4e4468',
      textMuted: '#6f6489',
      accent: '#6d4fc2',
      accentFg: '#ffffff',
      borderQuiet: '#d9d1ec',
      divider: '#e6e0f4',
      selectionBg: '#d7c9f5',
      selectionFg: '#2b2340',
      cursorColor: '#6d4fc2',
      sidebarBg: '#f5f1fc',
      editorCanvasBg: '#faf8fe',
      editorTextColor: '#2b2340',
      linkColor: '#5a3fb0',
      codeBg: '#e7e0f5',
      blockquoteBorder: '#a58fe0',
      colorSuccess: '#3e7d52',
      colorWarning: '#9e6d22',
      colorError: '#b03050',
      focusRing: 'rgba(109, 79, 194, 0.4)',
      modalOverlay: 'rgba(43, 35, 64, 0.45)',
      statusBarBg: '#f5f1fc',
      scrollbarThumb: '#b9abd9',
    },
  },

  sage_field: {
    id: 'sage_field',
    name: 'Sage Field',
    description: 'Sunlit meadow greens with deep botanical ink',
    mode: 'light',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_HUMAN,
      baseSizePx: 17, lineHeight: 1.8, maxWidthPx: 810,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#edf2ea', '#f8fbf7', '#3f6b4f'],
    tokens: {
      appBg: '#edf2ea',
      appSurface: '#f8fbf7',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#1e2b22',
      textSecondary: '#3d5245',
      textMuted: '#5d7466',
      accent: '#3f6b4f',
      accentFg: '#ffffff',
      borderQuiet: '#cbd8cb',
      divider: '#dde7dd',
      selectionBg: '#c4dcc9',
      selectionFg: '#1e2b22',
      cursorColor: '#3f6b4f',
      sidebarBg: '#f1f5ef',
      editorCanvasBg: '#f8fbf7',
      editorTextColor: '#1e2b22',
      linkColor: '#2f5a3e',
      codeBg: '#dfe9df',
      blockquoteBorder: '#7ba389',
      colorSuccess: '#2f7d44',
      colorWarning: '#96690f',
      colorError: '#a83232',
      focusRing: 'rgba(63, 107, 79, 0.4)',
      modalOverlay: 'rgba(30, 43, 34, 0.45)',
      statusBarBg: '#f1f5ef',
      scrollbarThumb: '#a9bfae',
    },
  },

  maritime_chart: {
    id: 'maritime_chart',
    name: 'Maritime Chart',
    description: 'Nautical parchment blues for plotting long voyages',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 17, lineHeight: 1.8, maxWidthPx: 800,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#eaf1f4', '#f7fafb', '#0e6e8e'],
    tokens: {
      appBg: '#eaf1f4',
      appSurface: '#f7fafb',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#16283a',
      textSecondary: '#38506a',
      textMuted: '#57708a',
      accent: '#0e6e8e',
      accentFg: '#ffffff',
      borderQuiet: '#c3d5de',
      divider: '#d8e4ea',
      selectionBg: '#bfe0ec',
      selectionFg: '#16283a',
      cursorColor: '#0e6e8e',
      sidebarBg: '#eff4f6',
      editorCanvasBg: '#f7fafb',
      editorTextColor: '#16283a',
      linkColor: '#0b5f7b',
      codeBg: '#dbe7ed',
      blockquoteBorder: '#5aa3b8',
      colorSuccess: '#2e7d4f',
      colorWarning: '#9a6a10',
      colorError: '#b03030',
      focusRing: 'rgba(14, 110, 142, 0.4)',
      modalOverlay: 'rgba(22, 40, 58, 0.45)',
      statusBarBg: '#eff4f6',
      scrollbarThumb: '#9db9c6',
    },
  },

  sandstone: {
    id: 'sandstone',
    name: 'Sandstone',
    description: 'Warm desert rock strata with bronze canyon accents',
    mode: 'light',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SERIF_BOOK,
      baseSizePx: 17, lineHeight: 1.8, maxWidthPx: 790,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#f0e8d8', '#faf5ea', '#8a5a1e'],
    tokens: {
      appBg: '#f0e8d8',
      appSurface: '#faf5ea',
      appSurfaceElevated: '#fffdf6',
      textPrimary: '#332619',
      textSecondary: '#57452e',
      textMuted: '#6f5d45',
      accent: '#8a5a1e',
      accentFg: '#ffffff',
      borderQuiet: '#d9c8a8',
      divider: '#e6d9bd',
      selectionBg: '#e8cf9e',
      selectionFg: '#332619',
      cursorColor: '#8a5a1e',
      sidebarBg: '#f4ecdd',
      editorCanvasBg: '#faf5ea',
      editorTextColor: '#332619',
      linkColor: '#744a16',
      codeBg: '#e7d9bd',
      blockquoteBorder: '#b08d4f',
      colorSuccess: '#46703f',
      colorWarning: '#96690f',
      colorError: '#a03525',
      focusRing: 'rgba(138, 90, 30, 0.4)',
      modalOverlay: 'rgba(51, 38, 25, 0.45)',
      statusBarBg: '#f4ecdd',
      scrollbarThumb: '#c4ab7d',
    },
  },

  porcelain: {
    id: 'porcelain',
    name: 'Porcelain',
    description: 'Cool gallery whites with celadon glaze details',
    mode: 'light',
    moodGroup: 'Studio Essentials',
    typography: {
      bodyStack: STACK_SANS_HUMAN,
      headingStack: STACK_SANS_HUMAN,
      baseSizePx: 16, lineHeight: 1.7, maxWidthPx: 830,
      paragraph: 'compact', indent: false,
    },
    swatchColors: ['#eef1f3', '#ffffff', '#2f6f8f'],
    tokens: {
      appBg: '#eef1f3',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#1c2733',
      textSecondary: '#3f4f60',
      textMuted: '#5a6b7c',
      accent: '#2f6f8f',
      accentFg: '#ffffff',
      borderQuiet: '#cfd8df',
      divider: '#e0e6eb',
      selectionBg: '#c2dde9',
      selectionFg: '#1c2733',
      cursorColor: '#2f6f8f',
      sidebarBg: '#f5f7f9',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#1c2733',
      linkColor: '#256984',
      codeBg: '#e3e9ee',
      blockquoteBorder: '#7fa8ba',
      colorSuccess: '#2e7d4f',
      colorWarning: '#96690f',
      colorError: '#b03030',
      focusRing: 'rgba(47, 111, 143, 0.4)',
      modalOverlay: 'rgba(28, 39, 51, 0.45)',
      statusBarBg: '#f5f7f9',
      scrollbarThumb: '#a7b6c2',
    },
  },

  honeyed_manuscript: {
    id: 'honeyed_manuscript',
    name: 'Honeyed Manuscript',
    description: 'Golden-hour vellum with amber marginalia warmth',
    mode: 'light',
    moodGroup: 'Paper & Print',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SERIF_WARM,
      baseSizePx: 18, lineHeight: 1.9, maxWidthPx: 790,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#f7edd4', '#fdf8ea', '#8a5f00'],
    tokens: {
      appBg: '#f7edd4',
      appSurface: '#fdf8ea',
      appSurfaceElevated: '#fffef8',
      textPrimary: '#3a2c14',
      textSecondary: '#5c4c28',
      textMuted: '#6e5f3f',
      accent: '#8a5f00',
      accentFg: '#ffffff',
      borderQuiet: '#e2d0a0',
      divider: '#eee0b8',
      selectionBg: '#f0d48a',
      selectionFg: '#3a2c14',
      cursorColor: '#8a5f00',
      sidebarBg: '#faf1da',
      editorCanvasBg: '#fdf8ea',
      editorTextColor: '#3a2c14',
      linkColor: '#755200',
      codeBg: '#efe0b4',
      blockquoteBorder: '#c09a3e',
      colorSuccess: '#4a7040',
      colorWarning: '#8a5f00',
      colorError: '#a03525',
      focusRing: 'rgba(138, 95, 0, 0.4)',
      modalOverlay: 'rgba(58, 44, 20, 0.45)',
      statusBarBg: '#faf1da',
      scrollbarThumb: '#cbb172',
    },
  },

  ember_study: {
    id: 'ember_study',
    name: 'Ember Study',
    description: 'Lamplit leather armchair with glowing amber embers',
    mode: 'dark',
    moodGroup: 'Gothic & Moody',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_HUMAN,
      baseSizePx: 18, lineHeight: 1.9, maxWidthPx: 800,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#171310', '#221c17', '#f59e0b'],
    tokens: {
      appBg: '#171310',
      appSurface: '#221c17',
      appSurfaceElevated: '#2e2520',
      textPrimary: '#f5e9dc',
      textSecondary: '#d3bda4',
      textMuted: '#a89278',
      accent: '#f59e0b',
      accentFg: '#171310',
      borderQuiet: '#453626',
      divider: '#2b231b',
      selectionBg: '#5c451f',
      selectionFg: '#ffe9c2',
      cursorColor: '#f59e0b',
      sidebarBg: '#1b1512',
      editorCanvasBg: '#221c17',
      editorTextColor: '#f5e9dc',
      linkColor: '#fbbf24',
      codeBg: '#1b1512',
      blockquoteBorder: '#b45309',
      colorSuccess: '#4ade80',
      colorWarning: '#f59e0b',
      colorError: '#f87171',
      focusRing: 'rgba(245, 158, 11, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#1b1512',
      scrollbarThumb: '#57432e',
    },
  },

  abyssal_ink: {
    id: 'abyssal_ink',
    name: 'Abyssal Ink',
    description: 'Deep-sea trench blacks with bioluminescent cyan',
    mode: 'dark',
    moodGroup: 'Night Writing',
    typography: {
      bodyStack: STACK_MONO,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 15, lineHeight: 1.8, maxWidthPx: 800,
      paragraph: 'compact', indent: false,
    },
    swatchColors: ['#0a0f1e', '#111a30', '#38bdf8'],
    tokens: {
      appBg: '#0a0f1e',
      appSurface: '#111a30',
      appSurfaceElevated: '#182441',
      textPrimary: '#e2e8f0',
      textSecondary: '#a9bccd',
      textMuted: '#7e93a9',
      accent: '#38bdf8',
      accentFg: '#0a0f1e',
      borderQuiet: '#22314f',
      divider: '#16203a',
      selectionBg: '#1d3a5f',
      selectionFg: '#e0f2fe',
      cursorColor: '#38bdf8',
      sidebarBg: '#0d1327',
      editorCanvasBg: '#111a30',
      editorTextColor: '#e2e8f0',
      linkColor: '#38bdf8',
      codeBg: '#0d1327',
      blockquoteBorder: '#0ea5e9',
      colorSuccess: '#34d399',
      colorWarning: '#fbbf24',
      colorError: '#fb7185',
      focusRing: 'rgba(56, 189, 248, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#0d1327',
      scrollbarThumb: '#2c3f63',
    },
  },

  moss_fog: {
    id: 'moss_fog',
    name: 'Moss & Fog',
    description: 'Mist hanging over wet stone and soft green light',
    mode: 'dark',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_HUMAN,
      baseSizePx: 17, lineHeight: 1.85, maxWidthPx: 810,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#101815', '#182420', '#7fd1a8'],
    tokens: {
      appBg: '#101815',
      appSurface: '#182420',
      appSurfaceElevated: '#213129',
      textPrimary: '#e6f0e8',
      textSecondary: '#b3c9bb',
      textMuted: '#87a294',
      accent: '#7fd1a8',
      accentFg: '#101815',
      borderQuiet: '#2b3f34',
      divider: '#1d2b23',
      selectionBg: '#2b4a3a',
      selectionFg: '#e6f5ec',
      cursorColor: '#7fd1a8',
      sidebarBg: '#131d18',
      editorCanvasBg: '#182420',
      editorTextColor: '#e6f0e8',
      linkColor: '#6ee7a8',
      codeBg: '#131d18',
      blockquoteBorder: '#34d399',
      colorSuccess: '#4ade80',
      colorWarning: '#fbbf24',
      colorError: '#f87171',
      focusRing: 'rgba(127, 209, 168, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#131d18',
      scrollbarThumb: '#37503f',
    },
  },

  oxblood_library: {
    id: 'oxblood_library',
    name: 'Oxblood Library',
    description: 'Leather-bound stacks with brass lamp and claret glow',
    mode: 'dark',
    moodGroup: 'Gothic & Moody',
    typography: {
      bodyStack: STACK_SERIF_BOOK,
      headingStack: STACK_SERIF_BOOK,
      baseSizePx: 17, lineHeight: 1.8, maxWidthPx: 790,
      paragraph: 'indented', indent: true,
    },
    swatchColors: ['#1a1114', '#26161c', '#e11d48'],
    tokens: {
      appBg: '#1a1114',
      appSurface: '#26161c',
      appSurfaceElevated: '#352027',
      textPrimary: '#f3e2e4',
      textSecondary: '#d3a9b1',
      textMuted: '#a88089',
      accent: '#e11d48',
      accentFg: '#ffffff',
      borderQuiet: '#4a2731',
      divider: '#2e1b21',
      selectionBg: '#5c1f2e',
      selectionFg: '#ffe4e6',
      cursorColor: '#fb4d6d',
      sidebarBg: '#201317',
      editorCanvasBg: '#26161c',
      editorTextColor: '#f3e2e4',
      linkColor: '#fb7185',
      codeBg: '#201317',
      blockquoteBorder: '#be123c',
      colorSuccess: '#4ade80',
      colorWarning: '#fbbf24',
      colorError: '#f87171',
      focusRing: 'rgba(225, 29, 72, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.8)',
      statusBarBg: '#201317',
      scrollbarThumb: '#5a3140',
    },
  },

  midnight_garden: {
    id: 'midnight_garden',
    name: 'Midnight Garden',
    description: 'Moonlit conservatory — deep teal leaves, pale blooms',
    mode: 'dark',
    moodGroup: 'Calm & Natural',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SANS_CLEAN,
      baseSizePx: 17, lineHeight: 1.85, maxWidthPx: 810,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#0e1420', '#16202f', '#4ade80'],
    tokens: {
      appBg: '#0e1420',
      appSurface: '#16202f',
      appSurfaceElevated: '#1f2d40',
      textPrimary: '#e3ecdf',
      textSecondary: '#a9bfae',
      textMuted: '#7d93a3',
      accent: '#4ade80',
      accentFg: '#0e1420',
      borderQuiet: '#2a3a4e',
      divider: '#1b2839',
      selectionBg: '#234434',
      selectionFg: '#dcfce7',
      cursorColor: '#4ade80',
      sidebarBg: '#111927',
      editorCanvasBg: '#16202f',
      editorTextColor: '#e3ecdf',
      linkColor: '#6ee7a8',
      codeBg: '#111927',
      blockquoteBorder: '#22c55e',
      colorSuccess: '#4ade80',
      colorWarning: '#fbbf24',
      colorError: '#fb7185',
      focusRing: 'rgba(74, 222, 128, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#111927',
      scrollbarThumb: '#33475d',
    },
  },

  lamplight: {
    id: 'lamplight',
    name: 'Lamplight',
    description: 'Folio after dark — warm parchment ink on ember brown with amber light',
    mode: 'dark',
    moodGroup: 'Night Writing',
    typography: {
      bodyStack: STACK_SERIF_WARM,
      headingStack: STACK_SERIF_WARM,
      baseSizePx: 18, lineHeight: 1.9, maxWidthPx: 790,
      paragraph: 'spacious', indent: false,
    },
    swatchColors: ['#14100c', '#1d1712', '#e0a458'],
    tokens: {
      appBg: '#14100c',
      appSurface: '#1d1712',
      appSurfaceElevated: '#261e16',
      textPrimary: '#ece1cd',
      textSecondary: '#c9b896',
      textMuted: '#8a7a5f',
      accent: '#e0a458',
      accentFg: '#14100c',
      borderQuiet: '#372b20',
      divider: '#241c14',
      selectionBg: '#54402a',
      selectionFg: '#ffe9c2',
      cursorColor: '#e0a458',
      sidebarBg: '#171310',
      editorCanvasBg: '#1d1712',
      editorTextColor: '#ece1cd',
      linkColor: '#e8b96a',
      codeBg: '#171310',
      blockquoteBorder: '#c9a13b',
      colorSuccess: '#4ade80',
      colorWarning: '#f59e0b',
      colorError: '#f87171',
      focusRing: 'rgba(224, 164, 88, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#171310',
      scrollbarThumb: '#4a3a28',
    },
  },

  graphite_mono: {
    id: 'graphite_mono',
    name: 'Graphite Mono',
    description: 'Drafting-table graphite with terminal-green precision',
    mode: 'dark',
    moodGroup: 'Studio Essentials',
    typography: {
      bodyStack: STACK_MONO,
      headingStack: STACK_MONO,
      baseSizePx: 15, lineHeight: 1.8, maxWidthPx: 840,
      paragraph: 'compact', indent: false,
    },
    swatchColors: ['#101012', '#1a1a1e', '#4ade80'],
    tokens: {
      appBg: '#101012',
      appSurface: '#1a1a1e',
      appSurfaceElevated: '#26262c',
      textPrimary: '#f4f4f5',
      textSecondary: '#c9c9d1',
      textMuted: '#9d9daa',
      accent: '#4ade80',
      accentFg: '#101012',
      borderQuiet: '#333338',
      divider: '#222227',
      selectionBg: '#234434',
      selectionFg: '#dcfce7',
      cursorColor: '#4ade80',
      sidebarBg: '#141416',
      editorCanvasBg: '#1a1a1e',
      editorTextColor: '#f4f4f5',
      linkColor: '#6ee7a8',
      codeBg: '#141416',
      blockquoteBorder: '#52525b',
      colorSuccess: '#4ade80',
      colorWarning: '#facc15',
      colorError: '#f87171',
      focusRing: 'rgba(74, 222, 128, 0.45)',
      modalOverlay: 'rgba(0, 0, 0, 0.8)',
      statusBarBg: '#141416',
      scrollbarThumb: '#3f3f46',
    },
  },
};

export const THEME_IDS: ThemeId[] = [
  'studio',
  'oled',
  'cyberpunk',
  'nord',
  'solarized',
  'nordic_day',
  'literary',
  'typewriter',
  'ink_and_paper',
  'midnight_blue',
  'forest_night',
  'sepia_desk',
  'crimson_gothic',
  'arctic_light',
  'monochrome',
  'newsprint',
  'lavender_morning',
  'sage_field',
  'maritime_chart',
  'sandstone',
  'porcelain',
  'honeyed_manuscript',
  'ember_study',
  'abyssal_ink',
  'moss_fog',
  'oxblood_library',
  'midnight_garden',
  'graphite_mono',
  'lamplight',
];

export function getTheme(themeId: string): ThemeDefinition {
  return THEMES[themeId as ThemeId] || THEMES.studio;
}

export function themeTokensToCssVariables(theme: ThemeDefinition): Record<string, string> {
  const { tokens } = theme;
  return {
    '--app-bg': tokens.appBg,
    '--app-surface': tokens.appSurface,
    '--app-surface-elevated': tokens.appSurfaceElevated,
    '--text-primary': tokens.textPrimary,
    '--text-secondary': tokens.textSecondary,
    '--text-muted': tokens.textMuted,
    '--accent': tokens.accent,
    '--accent-fg': tokens.accentFg,
    '--border-quiet': tokens.borderQuiet,
    '--divider': tokens.divider,
    '--selection-bg': tokens.selectionBg,
    '--selection-fg': tokens.selectionFg,
    '--cursor-color': tokens.cursorColor,
    '--sidebar-bg': tokens.sidebarBg,
    '--editor-canvas-bg': tokens.editorCanvasBg,
    '--editor-text-color': tokens.editorTextColor,
    '--link-color': tokens.linkColor,
    '--code-bg': tokens.codeBg,
    '--blockquote-border': tokens.blockquoteBorder,
    '--color-success': tokens.colorSuccess,
    '--color-warning': tokens.colorWarning,
    '--color-error': tokens.colorError,
    '--focus-ring': tokens.focusRing,
    '--modal-overlay': tokens.modalOverlay,
    '--status-bar-bg': tokens.statusBarBg,
    '--scrollbar-thumb': tokens.scrollbarThumb,

    // Backwards-compatible aliases with shell.css & editor.css
    '--bg-desk': tokens.appBg,
    '--bg-page': tokens.editorCanvasBg,
    '--text-ink': tokens.editorTextColor,
    '--text-faint': tokens.textMuted,
    '--accent-soft': tokens.accent,

    // Bundled editor typography (optional per theme; absent = keep current preset)
    ...(theme.typography ? themeTypographyToVars(theme.typography) : {}),
  };
}
