import { ThemeDefinition, ThemeId } from './types';

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  studio: {
    id: 'studio',
    name: 'Studio',
    description: 'Clean, neutral desk with balanced slate accents',
    mode: 'light',
    swatchColors: ['#f9f8f6', '#ffffff', '#4a5568'],
    tokens: {
      appBg: '#f9f8f6',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#2b2b2b',
      textSecondary: '#5a5855',
      textMuted: '#8c8983',
      accent: '#4a5568',
      accentFg: '#ffffff',
      borderQuiet: '#eae7e1',
      divider: '#f0ede6',
      selectionBg: '#dbeafe',
      selectionFg: '#1e3a8a',
      cursorColor: '#2b2b2b',
      sidebarBg: '#ffffff',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#2b2b2b',
      linkColor: '#2563eb',
      codeBg: '#f3f0e8',
      blockquoteBorder: '#cbd5e1',
      colorSuccess: '#10b981',
      colorWarning: '#f59e0b',
      colorError: '#ef4444',
      focusRing: 'rgba(74, 85, 104, 0.4)',
      modalOverlay: 'rgba(0, 0, 0, 0.45)',
      statusBarBg: '#ffffff',
      scrollbarThumb: '#d1cdc4',
    },
  },

  oled: {
    id: 'oled',
    name: 'OLED Black',
    description: 'Pure pitch black for minimum eye fatigue and true OLED screens',
    mode: 'dark',
    swatchColors: ['#000000', '#0a0a0a', '#60a5fa'],
    tokens: {
      appBg: '#000000',
      appSurface: '#080808',
      appSurfaceElevated: '#121212',
      textPrimary: '#f3f4f6',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
      accent: '#60a5fa',
      accentFg: '#000000',
      borderQuiet: '#1f2937',
      divider: '#111827',
      selectionBg: '#1e3a8a',
      selectionFg: '#ffffff',
      cursorColor: '#60a5fa',
      sidebarBg: '#000000',
      editorCanvasBg: '#080808',
      editorTextColor: '#f3f4f6',
      linkColor: '#93c5fd',
      codeBg: '#111827',
      blockquoteBorder: '#374151',
      colorSuccess: '#34d399',
      colorWarning: '#fbbf24',
      colorError: '#f87171',
      focusRing: 'rgba(96, 165, 250, 0.5)',
      modalOverlay: 'rgba(0, 0, 0, 0.85)',
      statusBarBg: '#000000',
      scrollbarThumb: '#374151',
    },
  },

  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Electric neon cyan & magenta across dark obsidian night',
    mode: 'dark',
    swatchColors: ['#0d0e15', '#161826', '#00f0ff'],
    tokens: {
      appBg: '#0d0e15',
      appSurface: '#161826',
      appSurfaceElevated: '#1f2338',
      textPrimary: '#f0f6fc',
      textSecondary: '#a5b4fc',
      textMuted: '#6366f1',
      accent: '#00f0ff',
      accentFg: '#050811',
      borderQuiet: '#2a2f4c',
      divider: '#1e2238',
      selectionBg: '#ff007f',
      selectionFg: '#ffffff',
      cursorColor: '#00f0ff',
      sidebarBg: '#12141f',
      editorCanvasBg: '#161826',
      editorTextColor: '#f0f6fc',
      linkColor: '#00f0ff',
      codeBg: '#1e2238',
      blockquoteBorder: '#ff007f',
      colorSuccess: '#00ff66',
      colorWarning: '#ffb700',
      colorError: '#ff0055',
      focusRing: 'rgba(0, 240, 255, 0.5)',
      modalOverlay: 'rgba(5, 8, 17, 0.8)',
      statusBarBg: '#12141f',
      scrollbarThumb: '#3b426b',
    },
  },

  nord: {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic blue-grey tones inspired by Scandinavian landscapes',
    mode: 'dark',
    swatchColors: ['#2e3440', '#3b4252', '#88c0d0'],
    tokens: {
      appBg: '#2e3440',
      appSurface: '#3b4252',
      appSurfaceElevated: '#434c5e',
      textPrimary: '#eceff4',
      textSecondary: '#d8dee9',
      textMuted: '#e5e9f0',
      accent: '#88c0d0',
      accentFg: '#2e3440',
      borderQuiet: '#4c566a',
      divider: '#3b4252',
      selectionBg: '#434c5e',
      selectionFg: '#88c0d0',
      cursorColor: '#88c0d0',
      sidebarBg: '#2e3440',
      editorCanvasBg: '#3b4252',
      editorTextColor: '#eceff4',
      linkColor: '#81a1c1',
      codeBg: '#2e3440',
      blockquoteBorder: '#81a1c1',
      colorSuccess: '#a3be8c',
      colorWarning: '#ebcb8b',
      colorError: '#bf616a',
      focusRing: 'rgba(136, 192, 208, 0.4)',
      modalOverlay: 'rgba(46, 52, 64, 0.75)',
      statusBarBg: '#2e3440',
      scrollbarThumb: '#4c566a',
    },
  },

  solarized: {
    id: 'solarized',
    name: 'Solarized Dark',
    description: 'Precision-calculated warm dark palette with amber and cyan highlights',
    mode: 'dark',
    swatchColors: ['#002b36', '#073642', '#b58900'],
    tokens: {
      appBg: '#002b36',
      appSurface: '#073642',
      appSurfaceElevated: '#0a4250',
      textPrimary: '#93a1a1',
      textSecondary: '#839496',
      textMuted: '#586e75',
      accent: '#b58900',
      accentFg: '#002b36',
      borderQuiet: '#0e5264',
      divider: '#073642',
      selectionBg: '#073642',
      selectionFg: '#eee8d5',
      cursorColor: '#268bd2',
      sidebarBg: '#002b36',
      editorCanvasBg: '#073642',
      editorTextColor: '#93a1a1',
      linkColor: '#268bd2',
      codeBg: '#002b36',
      blockquoteBorder: '#2aa198',
      colorSuccess: '#859900',
      colorWarning: '#cb4b16',
      colorError: '#dc322f',
      focusRing: 'rgba(181, 137, 0, 0.4)',
      modalOverlay: 'rgba(0, 43, 54, 0.8)',
      statusBarBg: '#002b36',
      scrollbarThumb: '#0e5264',
    },
  },

  nordic_day: {
    id: 'nordic_day',
    name: 'Nordic Day',
    description: 'Crisp, bright snow aesthetic with glacial blue accents',
    mode: 'light',
    swatchColors: ['#eceff4', '#ffffff', '#5e81ac'],
    tokens: {
      appBg: '#eceff4',
      appSurface: '#ffffff',
      appSurfaceElevated: '#f8fafc',
      textPrimary: '#2e3440',
      textSecondary: '#4c566a',
      textMuted: '#7c8b9e',
      accent: '#5e81ac',
      accentFg: '#ffffff',
      borderQuiet: '#d8dee9',
      divider: '#e5e9f0',
      selectionBg: '#d8dee9',
      selectionFg: '#2e3440',
      cursorColor: '#5e81ac',
      sidebarBg: '#ffffff',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#2e3440',
      linkColor: '#5e81ac',
      codeBg: '#e5e9f0',
      blockquoteBorder: '#88c0d0',
      colorSuccess: '#a3be8c',
      colorWarning: '#ebcb8b',
      colorError: '#bf616a',
      focusRing: 'rgba(94, 129, 172, 0.4)',
      modalOverlay: 'rgba(46, 52, 64, 0.4)',
      statusBarBg: '#ffffff',
      scrollbarThumb: '#c2cad6',
    },
  },

  literary: {
    id: 'literary',
    name: 'Literary',
    description: 'Warm cream, soft amber, and deep bookish ink',
    mode: 'light',
    swatchColors: ['#fbf0d9', '#fff9ed', '#8c5e3c'],
    tokens: {
      appBg: '#fbf0d9',
      appSurface: '#fff9ed',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#3d2b1f',
      textSecondary: '#6e5442',
      textMuted: '#9e8470',
      accent: '#8c5e3c',
      accentFg: '#ffffff',
      borderQuiet: '#eddcc2',
      divider: '#f5e9d3',
      selectionBg: '#edd9b9',
      selectionFg: '#3d2b1f',
      cursorColor: '#8c5e3c',
      sidebarBg: '#fdf6e7',
      editorCanvasBg: '#fff9ed',
      editorTextColor: '#3d2b1f',
      linkColor: '#9c411d',
      codeBg: '#f3e4cb',
      blockquoteBorder: '#bfa07d',
      colorSuccess: '#4d8055',
      colorWarning: '#c77826',
      colorError: '#ad372b',
      focusRing: 'rgba(140, 94, 60, 0.4)',
      modalOverlay: 'rgba(61, 43, 31, 0.45)',
      statusBarBg: '#fdf6e7',
      scrollbarThumb: '#dbc7aa',
    },
  },

  typewriter: {
    id: 'typewriter',
    name: 'Typewriter Desk',
    description: 'Classic vintage newsroom paper and ribbon monochrome',
    mode: 'light',
    swatchColors: ['#eae6df', '#f4f1ea', '#333333'],
    tokens: {
      appBg: '#eae6df',
      appSurface: '#f4f1ea',
      appSurfaceElevated: '#faf8f4',
      textPrimary: '#1a1a1a',
      textSecondary: '#4d4d4d',
      textMuted: '#808080',
      accent: '#333333',
      accentFg: '#ffffff',
      borderQuiet: '#d5cfc4',
      divider: '#dfdacd',
      selectionBg: '#d0c9bb',
      selectionFg: '#1a1a1a',
      cursorColor: '#000000',
      sidebarBg: '#eeeae2',
      editorCanvasBg: '#f4f1ea',
      editorTextColor: '#1a1a1a',
      linkColor: '#1a1a1a',
      codeBg: '#ded8cc',
      blockquoteBorder: '#736e65',
      colorSuccess: '#3e6b48',
      colorWarning: '#9e6d22',
      colorError: '#9e2d24',
      focusRing: 'rgba(51, 51, 51, 0.4)',
      modalOverlay: 'rgba(26, 26, 26, 0.5)',
      statusBarBg: '#eeeae2',
      scrollbarThumb: '#bfb8a8',
    },
  },

  ink_and_paper: {
    id: 'ink_and_paper',
    name: 'Ink & Paper',
    description: 'High-contrast stark print layout with editorial precision',
    mode: 'light',
    swatchColors: ['#f5f5f5', '#ffffff', '#000000'],
    tokens: {
      appBg: '#f5f5f5',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#000000',
      textSecondary: '#404040',
      textMuted: '#737373',
      accent: '#000000',
      accentFg: '#ffffff',
      borderQuiet: '#e0e0e0',
      divider: '#ebebeb',
      selectionBg: '#000000',
      selectionFg: '#ffffff',
      cursorColor: '#000000',
      sidebarBg: '#ffffff',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#000000',
      linkColor: '#000000',
      codeBg: '#ebebeb',
      blockquoteBorder: '#000000',
      colorSuccess: '#16a34a',
      colorWarning: '#ca8a04',
      colorError: '#dc2626',
      focusRing: 'rgba(0, 0, 0, 0.6)',
      modalOverlay: 'rgba(0, 0, 0, 0.6)',
      statusBarBg: '#ffffff',
      scrollbarThumb: '#b3b3b3',
    },
  },

  midnight_blue: {
    id: 'midnight_blue',
    name: 'Midnight Blue',
    description: 'Deep oceanic indigo night with crisp starlight accents',
    mode: 'dark',
    swatchColors: ['#0b132b', '#1c2541', '#48cae4'],
    tokens: {
      appBg: '#0b132b',
      appSurface: '#1c2541',
      appSurfaceElevated: '#243054',
      textPrimary: '#e0f2fe',
      textSecondary: '#93c5fd',
      textMuted: '#60a5fa',
      accent: '#48cae4',
      accentFg: '#0b132b',
      borderQuiet: '#2c3a66',
      divider: '#1f2b4e',
      selectionBg: '#3a506b',
      selectionFg: '#ffffff',
      cursorColor: '#48cae4',
      sidebarBg: '#111a36',
      editorCanvasBg: '#1c2541',
      editorTextColor: '#e0f2fe',
      linkColor: '#38bdf8',
      codeBg: '#111a36',
      blockquoteBorder: '#48cae4',
      colorSuccess: '#2dd4bf',
      colorWarning: '#f59e0b',
      colorError: '#fb7185',
      focusRing: 'rgba(72, 202, 228, 0.45)',
      modalOverlay: 'rgba(11, 19, 43, 0.8)',
      statusBarBg: '#111a36',
      scrollbarThumb: '#3a506b',
    },
  },

  forest_night: {
    id: 'forest_night',
    name: 'Forest Night',
    description: 'Evergreen pine, moss shadow, and gentle golden firefly glow',
    mode: 'dark',
    swatchColors: ['#131c15', '#1e2d22', '#a3cfbb'],
    tokens: {
      appBg: '#131c15',
      appSurface: '#1e2d22',
      appSurfaceElevated: '#283c2e',
      textPrimary: '#e8f5e9',
      textSecondary: '#a5d6a7',
      textMuted: '#66bb6a',
      accent: '#a3cfbb',
      accentFg: '#131c15',
      borderQuiet: '#2f4736',
      divider: '#203225',
      selectionBg: '#2f4736',
      selectionFg: '#ffffff',
      cursorColor: '#a3cfbb',
      sidebarBg: '#162219',
      editorCanvasBg: '#1e2d22',
      editorTextColor: '#e8f5e9',
      linkColor: '#81c784',
      codeBg: '#162219',
      blockquoteBorder: '#81c784',
      colorSuccess: '#4caf50',
      colorWarning: '#ffca28',
      colorError: '#e57373',
      focusRing: 'rgba(163, 207, 187, 0.45)',
      modalOverlay: 'rgba(19, 28, 21, 0.8)',
      statusBarBg: '#162219',
      scrollbarThumb: '#3e5c46',
    },
  },

  sepia_desk: {
    id: 'sepia_desk',
    name: 'Sepia Desk',
    description: 'Rich vintage leather, warm antique paper, and bronze trims',
    mode: 'light',
    swatchColors: ['#ede0d4', '#f7ede2', '#7f5539'],
    tokens: {
      appBg: '#ede0d4',
      appSurface: '#f7ede2',
      appSurfaceElevated: '#fff6ec',
      textPrimary: '#43281c',
      textSecondary: '#6b442a',
      textMuted: '#9c6644',
      accent: '#7f5539',
      accentFg: '#ffffff',
      borderQuiet: '#ddb892',
      divider: '#e6ccb2',
      selectionBg: '#ddb892',
      selectionFg: '#43281c',
      cursorColor: '#7f5539',
      sidebarBg: '#f0e3d7',
      editorCanvasBg: '#f7ede2',
      editorTextColor: '#43281c',
      linkColor: '#9c6644',
      codeBg: '#e6ccb2',
      blockquoteBorder: '#7f5539',
      colorSuccess: '#588157',
      colorWarning: '#d48b38',
      colorError: '#bc4749',
      focusRing: 'rgba(127, 85, 57, 0.4)',
      modalOverlay: 'rgba(67, 40, 28, 0.5)',
      statusBarBg: '#f0e3d7',
      scrollbarThumb: '#cca378',
    },
  },

  crimson_gothic: {
    id: 'crimson_gothic',
    name: 'Crimson Gothic',
    description: 'Velvet burgundy, obsidian stone, and deep ruby luminescence',
    mode: 'dark',
    swatchColors: ['#161114', '#241a20', '#e63946'],
    tokens: {
      appBg: '#161114',
      appSurface: '#241a20',
      appSurfaceElevated: '#33232d',
      textPrimary: '#fae8eb',
      textSecondary: '#d8b4bc',
      textMuted: '#9e7580',
      accent: '#e63946',
      accentFg: '#ffffff',
      borderQuiet: '#422c39',
      divider: '#2a1e26',
      selectionBg: '#592938',
      selectionFg: '#ffffff',
      cursorColor: '#e63946',
      sidebarBg: '#1c151a',
      editorCanvasBg: '#241a20',
      editorTextColor: '#fae8eb',
      linkColor: '#ff4d6d',
      codeBg: '#1c151a',
      blockquoteBorder: '#e63946',
      colorSuccess: '#52b788',
      colorWarning: '#ee9b00',
      colorError: '#e63946',
      focusRing: 'rgba(230, 57, 70, 0.45)',
      modalOverlay: 'rgba(22, 17, 20, 0.85)',
      statusBarBg: '#1c151a',
      scrollbarThumb: '#4e3343',
    },
  },

  arctic_light: {
    id: 'arctic_light',
    name: 'Arctic Light',
    description: 'Ultra-crisp frost daylight with crystalline blue contrasts',
    mode: 'light',
    swatchColors: ['#f0f4f8', '#ffffff', '#0284c7'],
    tokens: {
      appBg: '#f0f4f8',
      appSurface: '#ffffff',
      appSurfaceElevated: '#ffffff',
      textPrimary: '#0f172a',
      textSecondary: '#334155',
      textMuted: '#64748b',
      accent: '#0284c7',
      accentFg: '#ffffff',
      borderQuiet: '#cbd5e1',
      divider: '#e2e8f0',
      selectionBg: '#bae6fd',
      selectionFg: '#0369a1',
      cursorColor: '#0284c7',
      sidebarBg: '#f8fafc',
      editorCanvasBg: '#ffffff',
      editorTextColor: '#0f172a',
      linkColor: '#0284c7',
      codeBg: '#e2e8f0',
      blockquoteBorder: '#38bdf8',
      colorSuccess: '#059669',
      colorWarning: '#d97706',
      colorError: '#e11d48',
      focusRing: 'rgba(2, 132, 199, 0.4)',
      modalOverlay: 'rgba(15, 23, 42, 0.45)',
      statusBarBg: '#f8fafc',
      scrollbarThumb: '#94a3b8',
    },
  },

  monochrome: {
    id: 'monochrome',
    name: 'Monochrome Slate',
    description: 'Minimalist pure grayscale with zero chromatic distraction',
    mode: 'dark',
    swatchColors: ['#18181b', '#27272a', '#a1a1aa'],
    tokens: {
      appBg: '#18181b',
      appSurface: '#27272a',
      appSurfaceElevated: '#3f3f46',
      textPrimary: '#fafafa',
      textSecondary: '#d4d4d8',
      textMuted: '#a1a1aa',
      accent: '#e4e4e7',
      accentFg: '#18181b',
      borderQuiet: '#3f3f46',
      divider: '#27272a',
      selectionBg: '#52525b',
      selectionFg: '#ffffff',
      cursorColor: '#ffffff',
      sidebarBg: '#1f1f23',
      editorCanvasBg: '#27272a',
      editorTextColor: '#fafafa',
      linkColor: '#e4e4e7',
      codeBg: '#18181b',
      blockquoteBorder: '#71717a',
      colorSuccess: '#4ade80',
      colorWarning: '#facc15',
      colorError: '#f87171',
      focusRing: 'rgba(228, 228, 231, 0.4)',
      modalOverlay: 'rgba(0, 0, 0, 0.75)',
      statusBarBg: '#1f1f23',
      scrollbarThumb: '#52525b',
    },
  },
};

export const THEME_IDS: ThemeId[] = [
  'studio',
  'oled',
  'cyberpunk',
  'nord',
  'solarized',
  'nordic_day',
  'literary',
  'typewriter',
  'ink_and_paper',
  'midnight_blue',
  'forest_night',
  'sepia_desk',
  'crimson_gothic',
  'arctic_light',
  'monochrome',
];

export function getTheme(themeId: string): ThemeDefinition {
  return THEMES[themeId as ThemeId] || THEMES.studio;
}

export function themeTokensToCssVariables(theme: ThemeDefinition): Record<string, string> {
  const { tokens } = theme;
  return {
    '--app-bg': tokens.appBg,
    '--app-surface': tokens.appSurface,
    '--app-surface-elevated': tokens.appSurfaceElevated,
    '--text-primary': tokens.textPrimary,
    '--text-secondary': tokens.textSecondary,
    '--text-muted': tokens.textMuted,
    '--accent': tokens.accent,
    '--accent-fg': tokens.accentFg,
    '--border-quiet': tokens.borderQuiet,
    '--divider': tokens.divider,
    '--selection-bg': tokens.selectionBg,
    '--selection-fg': tokens.selectionFg,
    '--cursor-color': tokens.cursorColor,
    '--sidebar-bg': tokens.sidebarBg,
    '--editor-canvas-bg': tokens.editorCanvasBg,
    '--editor-text-color': tokens.editorTextColor,
    '--link-color': tokens.linkColor,
    '--code-bg': tokens.codeBg,
    '--blockquote-border': tokens.blockquoteBorder,
    '--color-success': tokens.colorSuccess,
    '--color-warning': tokens.colorWarning,
    '--color-error': tokens.colorError,
    '--focus-ring': tokens.focusRing,
    '--modal-overlay': tokens.modalOverlay,
    '--status-bar-bg': tokens.statusBarBg,
    '--scrollbar-thumb': tokens.scrollbarThumb,

    // Backwards-compatible aliases with shell.css & editor.css
    '--bg-desk': tokens.appBg,
    '--bg-page': tokens.editorCanvasBg,
    '--text-ink': tokens.editorTextColor,
    '--text-faint': tokens.textMuted,
    '--accent-soft': tokens.accent,
  };
}
